### ISSUE TITLE
Third party users how to update the price？

### ISSUE THREAD

**Issue by JayenLee** [meertensm/amazon-mws#2]
Third party users how to update the price？

**Comment by meertensm** [comment]
Hi Jayen,

Working on it now.

**Comment by JayenLee** [comment]
Hi,Third party users  update the price ，need to  MWSAuthToken

**Comment by meertensm** [comment]
Jayen,

Just added the MWSAuthToken parameter to the construct array. Look at the readme. Because i'm not a third party developer, i can't test it.

Please let me know if you have any problem
