### ISSUE TITLE
Update Composer 

### ISSUE THREAD

**Issue by mavinbeh** [meertensm/amazon-mws#26]
Hello,
can you update, the Composer Repo to the newest Version?
That would be nice. Thank you.

Regards
Malte

**Comment by meertensm** [comment]
Hi,
It is the latest version.
<img width="888" alt="schermafbeelding 2018-01-12 om 10 24 51" src="https://user-images.githubusercontent.com/10245984/34868077-e4117b62-f782-11e7-90d2-f5a0494a4dbc.png">

**Comment by mabuak** [comment]
Hi,
If you need to the newest updated, you can use "mcs/amazon-mws": "dev-master".

**Comment by mavinbeh** [comment]
Hi, 

thank u. it works.

regards 
malte

——————————
Malte-Levin Behrens
malte.levin.behrens@gmail.com
0160 1765312
