### ISSUE TITLE
how to get reports thats not included in your repo

### ISSUE THREAD

**Issue by skooperss** [meertensm/amazon-mws#27]
I want to get sales report through _GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_.

**Comment by mabuak** [comment]
Hi @skooperss, 

You can used this to get the orders

// Returns orders created or updated during a time frame that you specify.
$client->ListOrders($from, $allMarketplaces = false, $states = ['Unshipped', 'PartiallyShipped'], $FulfillmentChannel = 'MFN');
