### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by GrandNin-portequoi** [meertensm/amazon-mws#3]
Hi,
got an error with Symfony 3.2.1 in localhost, with all methods i use : 

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

My credentials works with Amazon Scratchpad but not with this lib.
Any Idea ?

Thanks

**Comment by meertensm** [comment]
What endpoint are you accessing? And on what platform are you developing?

**Comment by GrandNin-portequoi** [comment]
Hi,
I'm using Symfony 3.2.1 on WAMP Server.
I already added cacert.pem to my php.ini file to resolve Curl SSL Error 60.

All Endpoints give this error.

**Comment by meertensm** [comment]
Fixed in 0.1.5. Had to do with PHP_EOL, which is different on Windows.

**Comment by pedrogrou** [comment]
I have the same error, but on production server (Ubuntu 16.04). 
It works on Windows XAMPP.
Any idea?
