### ISSUE TITLE
is Missing GetReportListByNextToken...

### ISSUE THREAD

**Issue by spainbox** [meertensm/amazon-mws#4]
I am getting list of reports unsorted and can read the last months orders...
do you plan include GetReportListByNextToken ?

THank you in advance!

**Comment by meertensm** [comment]
Hi spainbox,

At this time Get*ByNextToken functions are not used by this library. I'm honestly not planning to implement this in the near future because the project i built this library for never has that many results. Feel free to implement it yourself and submit a pull-request.
