### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by NerdGuruDevelopers** [meertensm/amazon-mws#45]
Hey so your code probably just saved me a few days of screwing around. Where do I send a donation?

**Comment by meertensm** [comment]
Hi!

You can donate through paypal. My account is meertensmichiel28@gmail.com

Thanks in advance,
Michiel

Op ma 21 mei 2018 om 04:32 schreef NerdGuruDevelopers <
notifications@github.com>:

**Comment by NerdGuruDevelopers** [comment]
Sent $30 or ~€25. Not much, but the code is appreciated.

**Comment by meertensm** [comment]
Thank you! I really appreciate it!

Op di 22 mei 2018 om 23:49 schreef NerdGuruDevelopers <
notifications@github.com>:

**Comment by Elompenta** [comment]
@meertensm I would use the buttons a few minutes ago.
You have selected NL Language in your donate Button :-}

I think it is a good idea to switch to "EN" - not all the people are understanding NL ;)
