### ISSUE TITLE
Uncaught exception 'Exception' with message 'Request is throttled'

### ISSUE THREAD

**Issue by Elompenta** [meertensm/amazon-mws#54]
I think is a good idea to catch the `Request is throttled` message.
@meertensm 
What do you think about a sleep timer and resend the API Call?

`PHP Fatal error:  Uncaught exception 'Exception' with message 'Request is throttled' in /var/.../amazon-mws/src/MWSClient.php:1294`

**Comment by augz** [comment]
When you reference a call you should have it wrapped in a try catch block, to which you should be catching and handling this behavior with app specific responses.

**Comment by Elompenta** [comment]
make sense.. ok sorry, i close the issue :)
