### ISSUE TITLE
Gives org.jboss.resteasy.spi.metadata error on GetLowestPricedOffersForASIN, here is a solution

### ISSUE THREAD

**Issue by Meeshalk** [meertensm/amazon-mws#76]
https://github.com/meertensm/amazon-mws/blob/2ec8eca6f27bc111a685c70c216d11882cbf9014/src/MWSClient.php#L1258

MWS needs POST data passed as form params and not of as a query string for **some operations**. Otherwise, it pukes a Failed processing arguments of org.jboss.resteasy.spi.metadata

This code will not work for method `GetLowestPricedOffersForASIN`

```
$response = $this->client->request(
    $endPoint['method'],
    $this->config['Region_Url'] . $endPoint['path'],
    $requestOptions
);
```

replace the above code with this one;

```
if($endPoint['action'] == 'GetLowestPricedOffersForASIN'){
    $response = $this->client->request(
        'POST',
         $this->config['Region_Url'] . $endPoint['path'],
         ['form_params' => $query]
      );
  }else{
      $response = $this->client->request(
          $endPoint['method'],
          $this->config['Region_Url'] . $endPoint['path'],
          $requestOptions
       );
   }
```

I hope it helped.

**Comment by neps-in** [comment]
Its working ! atleast for me

**Comment by BlackDeer** [comment]
Someone should do a pull request.

**Comment by Meeshalk** [comment]
I think this is solved as @BlackDeer mentioned
